### ISSUE TITLE
Explanation of the process

### ISSUE THREAD

**Issue by Niko464** [perseidesjs/medusa-admin-vite#1]
Hi,

This is a great repo to customize medusajs in more detail instead of using their plugin system.
I would like to know how you managed to get the source code of the latest UI ?

It seems like the only source code I can find is this:
https://github.com/medusajs/admin

Which is an old version, it has some bugs and the UI is different.

I can use the repository for my own project but I'd like to understand how you got the latest changes's source code, in order to not be dependant on you updating this repo in the future.

Thank you for any answer

**Comment by adevinwild** [comment]
Hi @Niko464 
I've updated the repo to `v1.20.10` just in case devs out here needs it for V1, thanks for letting me know!
So technically since it's just a React app, you just need to get the source code of the Admin UI inside the Medusa repo and replace it with the one inside the `src` folder inside this repo.

However, there is some things you need to know, for example you cannot use the `process.env` to get environment variables directly, you need to declare them inside the `vite.config.ts` and use them using the `__VAR__` syntax in your app.
So keep in mind this point when copy pasting the source files and make sure to search and replace all the ocurrences for the `process.env` that can be found inside the codebase 🙌

> **Nota bene** : I don't think there will be any major features in the future for V1 for the Admin UI, unless there are critical errors, but until then we'll have to look to Medusa V2

**Comment by adevinwild** [comment]
Just adding more context here, here is the repo I've used to get the `src` files : 
https://github.com/medusajs/medusa/tree/v1.20.10/packages/admin-ui/ui

Don't hesitate to comment, if you need more explanations or examples 🙌
